# Generated by Django 5.2.6 on 2025-09-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('recruiter', 'Recruiter'), ('student', 'Student'), ('placement_officer', 'Placement Officer')], default='student', max_length=20),
        ),
    ]
